language: go

go:
  - "1.13"

script:
  - go vet ./...
  - make test

before_deploy:
  - git config --local user.name "$USERNAME"
  - git config --local user.email "$EMAIL"
  - make release
  - export TRAVIS_TAG=$(grep -o "[0-9]\.[0-9]\.[0-9]"  Makefile)
  - export TRAVIS_ARTIFACT=$(ls *.tar.gz)
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: CQgbbuD8MAxyMjTHoOl9VCsL/0Fe7ymcMTf1N7hLZDccldHqZ+TWRdAy6Bo2c2GKh9Ck7SnIDw8JQwCe01w/EdtPLOQwnJ1GPk/sPgwccvVjJqtZVNisZByKQitPMUutmbT1PP/uZFO+TwcCMe86KUWuHuVWEgteG9PUJQC6anaMf628wiYJrgPi9Kw/mKIfiipNKffng0adNSSMiyfmNcp22CHYlEeJWZfEnS/daPaSBBdeEnzO4DBzWqw6cioS+RD7gmZMePY0s9wQz19D6Y9wLhpHREYZP6VhnJvHj0hBOwVlDbq/Ue29hh+UQHi+/Wfky63cQeKGudS5AQ/YS5oltEmzlM3CEc/4BacSgaXOiYSmLu5wxPfbpyLTLkMaVObvUpaFS71CCTxlZ2UnPS49iH1TsmjoBGM7kia59bKl87/bBkLzjEok+l6xwn1Wb2ik88TfXkwS4as5a1ayjbze5GCbFGom0WGX4rbVPFu7wKAvj163G5eJUK8836MDg1viEj7DktH+bCKWq0dKdfVutxD/gUpmo+EtsJDJ32tEtRFjxSl/PCoUbUjOSszHjHAXzAYvtW1jDrMmSClj6LxGzylfWaNGMwyDUZo4q0LFvhN+3vHu3B973CYvMslGC4QBbrFZ/iaC0o7NZx6G4iuFWiLA8qDeHE3+mHA0wZg=
  file: $TRAVIS_ARTIFACT
  skip_cleanup: true
  on:
    branch: master
